### ISSUE TITLE
problem creating new snippet

### ISSUE THREAD

**Issue by tryykx** [zjffun/vscode-snippets-manager#1]
May I know how to add to user's snippet directly instead of workplace

**Comment by zjffun** [comment]
I am also considering this feature. I am going to implement the feature that add a snippet to user's snippet by dragging the selected text to the sidebar items in the next version.

**Comment by zjffun** [comment]
According to [Add drag and drop for contributed tree views · Issue #32592 · microsoft/vscode](https://github.com/Microsoft/vscode/issues/32592), dnd cannot be implemented yet. So added another feature that create snippet to specified file.

This feature has been added to the v0.0.11

<img width="200px" src="https://user-images.githubusercontent.com/25266120/135716217-ca1eed44-eec4-45be-b7ff-f20bce06b24d.png">
