### ISSUE TITLE
Parse error output is not useful

### ISSUE THREAD

**Issue by ryanspain** [zjffun/vscode-snippets-manager#13]
**Addressed in PR #14.**

I'll explain this ~bug~ issue with reference to the below screenshot.

![image](https://user-images.githubusercontent.com/8723433/233726816-70ede968-8ade-4ded-938e-0ff4c9336edb.png)

1. If a snippet file fails to parse (e.g. because of a trailing comma).
2. The code snippet will not load in the Snippets Manager tab.
3. The output log for Snippets Manager only logs "_Parse error_".

I traced this error message to [CodeSnippetsService.ts](https://github.com/zjffun/vscode-snippets-manager/blob/42ddda8fb639763a506f02f8ad7977154ecbc408/src/CodeSnippetsService.ts#L86).

Ideally, the log should include at a minimum the snippet file name and line number to guide someone down the right path.

**Comment by zjffun** [comment]
I agree. Thank you for your PR.

**Comment by zjffun** [comment]
I merged the PR above, and update the message to correspond with the Status Bar. This will publish in next version. Thanks again.
<img width="957" alt="Screen Shot 2023-04-22 at 15 31 11" src="https://user-images.githubusercontent.com/25266120/233770077-0493ef28-aae9-4574-8d06-86ac5137867f.png">

**Comment by zjffun** [comment]
[Release v0.1.18](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.1.18) published. 🎉
