### ISSUE TITLE
Snippets on WSL

### ISSUE THREAD

**Issue by datvq** [zjffun/vscode-snippets-manager#19]
The problem with using WSL for development is that extension cannot be used on WSL if they are only installed on the Windows host. 

Therefore, you must install extensions on WSL and create snippets in the ~/.vscode-server/data/User/snippets directory for the extension to interact properly.

The issue is that VScode only suggests snippets from the snippets folder on the Windows host at C:\Users\your_name\AppData\Roaming\Code\User\snippets.

So the question is, can we simply install the extension on the Windows host and have it still be active on WSL, with all snippets managed on the Windows host?

Thanks for reading.

**Comment by zjffun** [comment]
We find this is a bug and fixed in [v0.2.1](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.2.1). 🎉

Thank you!

**Comment by datvq** [comment]
We are the ones who need to say thank you.
