### ISSUE TITLE
Please add copy&paste or drag&drop to the managers GUI

### ISSUE THREAD

**Issue by LukasGold** [zjffun/vscode-snippets-manager#20]
This is the best snippet manager I have found among all of the VS Code extensions. It provides exactly the editing features, I wanted to see (especially using the built-in snippets syntax). 

I want to suggest an enhancement: 
Could you please add drag&drop or copy&paste functionality so that snippets that have been created via right-click & "Create snippet" and are listed in the Workspace Snippets can easily be transferred to the User Snippets?

Thank you for consideration

**Comment by zjffun** [comment]
We investigated these two solutions and found that dragging and dropping cannot move snippets across trees (such as can't drag from the workspace to the user), so we are going to use copy and paste to complete this function. 

Now it's available in [v0.2.2](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.2.2) 🎉.

Thanks for your advice!

<img width="368" alt="Screen Shot 2023-06-17 at 01 36 12" src="https://github.com/zjffun/vscode-snippets-manager/assets/25266120/573b55a4-c374-40ce-9491-1b3f6710487a">

**Comment by LukasGold** [comment]
Hey there!

Thank you for the quick implementation. It works like a charm :)
