### ISSUE TITLE
Group command

### ISSUE THREAD

**Issue by LatenPath** [zjffun/vscode-snippets-manager#26]
Currently, this extension provides a list of command in right-click context menu:

![image](https://github.com/user-attachments/assets/b0e8844b-d8ae-4e29-b44d-d4d4aeea8475)

In my opinion, these commands (create snippet...) can be grouped into 1 "Snippet Manager ->", or else, like the one Spelling in the image. Then, it won't take too much space and easier to sort.

Thank you.

**Comment by zjffun** [comment]
@LatenPath Good suggestion, thank you. I released [v0.3.9](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.3.9) with this feature.

**Comment by LatenPath** [comment]
Thank you @zjffun, It's so great <3

![image](https://github.com/user-attachments/assets/3858f01f-6fd5-455b-96f1-b5ff53ee8bee)
