### ISSUE TITLE
Monospaced font

### ISSUE THREAD

**Issue by mmrsva** [zjffun/vscode-snippets-manager#28]
Is it possible to use a monospaced font in the snippets editor? To me, it shows a proportional font which is not the best when I want to create snippets and keep them aligned. I checked the settings but could not find an option for fonts.

**Comment by zjffun** [comment]
Sorry for the late reply. Great suggestion, I released [v0.3.10](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.3.10) to fix this. 🎉

**Comment by mmrsva** [comment]
Thank you very much!
