### ISSUE TITLE
Suggestion for describing further your nice extension functionalities

### ISSUE THREAD

**Issue by carloscadux** [zjffun/vscode-snippets-manager#3]
Hey zjffun!
Your extension is outstanding!
I'm a new VSCode user, and tried the native snippets system (which was difficult to grasp initially), then I tried several snippets extensions that provide their own snippets system. 

Just after installing your extension I could make sense of VSCode native snippets system and started using it properly. Thanks!

The description of your extension could be extended to emphasize it's qualities beyond only "Create and edit snippets easily".

Something like the following (English is not my mother tongue!):

This extension is built over the default VSCode snippets system, wrapping it into a nice and intuitive UI, improving usability, and making snippets easy to create and edit. It supports user-custom snippets, as well as global and thirdy-party snippets from installed languages. 

Cheers!
Carlos

**Comment by zjffun** [comment]
Good suggestion, I will revise the description in the next version. Thank you for your use and suggestion!

**Comment by zjffun** [comment]
Revised in https://github.com/zjffun/vscode-snippets-manager/commit/4a126d1df839aa0e418d6741875713a765d0015b 🙂
