### ISSUE TITLE
Awesome extension, but it does not work with symlinks.

### ISSUE THREAD

**Issue by sigajeff** [zjffun/vscode-snippets-manager#31]
Amazing extension. Congratulations! However, I cannot organize my snippets in the sidebar within the extension tab when referring to the snippets file through a symlink. Just a heads-up. If there is any solution, please let me know.

**Comment by zjffun** [comment]
Thank you for your report! I released [v0.3.12](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.3.12) to fix this. 🎉

**Comment by sigajeff** [comment]
Awesome!!  Looks amazing! Thank you very much ^^
