### ISSUE TITLE
💡suggestion: Can I add multiple prefixes like adding multiple  scopes in the editor view?💡

### ISSUE THREAD

**Issue by sincerely-hello-world** [zjffun/vscode-snippets-manager#32]
![image](https://github.com/user-attachments/assets/ac7aefaa-9b36-49a0-8434-d8323be760d1)

**Comment by zjffun** [comment]
We will need a few days to develop this, for now you can edit the prefix array using a text editor:

<img width="370" alt="Screenshot 2024-11-09 at 17 36 47" src="https://github.com/user-attachments/assets/db508259-f342-4d51-962a-958f1092c2cc">
<img width="439" alt="Screenshot 2024-11-09 at 17 42 16" src="https://github.com/user-attachments/assets/6d7c6057-3553-4c07-8de8-e56b873c7f60">

**Comment by zjffun** [comment]
We released [v0.3.15](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.3.15) to support this. 🎉 Thank you.
