### ISSUE TITLE
Suggestion: Clone/Duplicate Snippet functionality 

### ISSUE THREAD

**Issue by carloscadux** [zjffun/vscode-snippets-manager#4]
I'd suggest a Clone/Duplicate Snippet functionality, which would speed up the creation of the new snippets based on existing ones.
Regarding GUI, maybe an extra icon would do the job.
Thank you!

![image](https://user-images.githubusercontent.com/7339389/157067847-90b5de77-0d76-4e9b-81ed-187a096e9892.png)

**Comment by zjffun** [comment]
Good idea, I'll add it soon. We can click this button and open the duplication with edit state in editor.

**Comment by carloscadux** [comment]
> We can click this button and open the duplication with edit state in editor.

Perfect!

Also in the 'name' filed, if it is possible to automatically append 'cloned' suffix would be convenient to avoid the 
`Duplicate object key` error in advance.

![image](https://user-images.githubusercontent.com/7339389/157226894-cc0d8518-f5ca-4e6c-9066-514b3c12ef3e.png)

**Comment by zjffun** [comment]
There is a mechanism to prevent duplicate names that will trigger when saving snippets. If the same name is found, it will automatically add a number behind.

**Comment by zjffun** [comment]
Added in [Release v0.1.1](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.1.1) .

**Comment by carloscadux** [comment]
Tested. Many thanks for the improvement!
