### ISSUE TITLE
How to delete .json file?

### ISSUE THREAD

**Issue by LangLangBart** [zjffun/vscode-snippets-manager#5]
I appreciate this minimalistic extension for snippet management. I tried `Pieces` first, but installing additional software alongside the extension was a dealbreaker.

I have a trivial issue.
How do I delete the `xml.json` file?

<img src="https://ttm.sh/iaz.19.jpg" width="400">

An inconvenient way to delete them is to go to `~/Library/Application Support/Code/User/snippets`.

**Comment by LangLangBart** [comment]
`Easy Snippet` has a good UI option to quickly delete something.
<img src="https://ttm.sh/iaY.jpg" width="600">

**Comment by zjffun** [comment]
Good advice. We added this in [v0.1.2](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.1.2).

**Comment by LangLangBart** [comment]
Thank you so much for addressing this issue so quickly. It works fine.
