### ISSUE TITLE
Adding the snippets manager on open-VSX.org

### ISSUE THREAD

**Issue by TechJA** [zjffun/vscode-snippets-manager#6]
Hi
First of all, congrats on the snippets manager extension
I would ask you if you could add your extension also at [https://open-vsx.org/](https://open-vsx.org/) for VSCodium users

Thanks

**Comment by zjffun** [comment]
Good advice. I added it https://open-vsx.org/extension/zjffun/snippetsmanager. There is a warning now, so I'm claiming namespace https://github.com/EclipseFdn/open-vsx.org/issues/925.

**Comment by TechJA** [comment]
Hi zjffun,
Thank you
