### ISSUE TITLE
How to indent with tab?

### ISSUE THREAD

**Issue by yunsii** [zjffun/vscode-snippets-manager#7]
I use tab to indent code, when edit item, how to input tab? `\t` is not valid.

**Comment by yunsii** [comment]
I use show source to re-edit to workaround now 😂

**Comment by zjffun** [comment]
Seems a bug. I will fix it this weekend. Thank you.

**Comment by zjffun** [comment]
We added support to edit body in text editor in [v0.1.6](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.1.6).

For input tab:

1. Click this button
<img width="475" alt="image" src="https://user-images.githubusercontent.com/25266120/190853860-d0658ccd-fc50-4107-ac60-04fc6abdcf98.png">

2. Change indent type
<img width="598" alt="image" src="https://user-images.githubusercontent.com/25266120/190853921-906d2e5f-0e37-4529-bcf4-3187ddebf2bb.png">

3. Input tab
<img width="431" alt="image" src="https://user-images.githubusercontent.com/25266120/190853958-ea3498d3-0a8d-4227-b37e-8dab77812f58.png">
